### PR TITLE
Make ban and kick work without command blocks

### PR DESCRIPTION
**Pull request by 0x3C50**
was long needed

### CODE REVIEW

**Review by allinkdev — APPROVED** [review]
Great idea

**Comment by allinkdev** [comment]
https://user-images.githubusercontent.com/44676012/163186759-0a4754a1-b949-43cd-9b3a-761b33ce1f18.mp4

**Comment by veast-network** [comment]
IMG_0214

**Comment by eva67x** [comment]
image

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163187563-122adc59-5457-4e96-8cc3-b03843bfd47e.mp4

**Comment by allinkdev** [comment]
https://user-images.githubusercontent.com/44676012/163187667-73472e01-6faa-4903-b00b-c8c2de3b5867.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163187818-5dae76ff-a61d-469d-971c-f0903bd7a6d3.mp4

**Comment by allinkdev** [comment]
https://user-images.githubusercontent.com/44676012/163187850-97b16d6b-c07b-49ad-b5a4-43b0e7ea3aed.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163188078-5a508fd4-36fd-4375-b9f6-9264d5f26e1e.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163188143-75d6a785-ae14-4a9a-9077-88bdd7d7a7a9.mp4

**Comment by allinkdev** [comment]
https://user-images.githubusercontent.com/44676012/163188163-64ef87c6-54b2-4fb0-af6e-1f69a0ccc47c.mp4

**Comment by veast-network** [comment]
https://user-images.githubusercontent.com/86145902/163188272-b4513faf-1756-4fd8-9319-82a746ebe60e.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163188327-4e7fb070-75fd-41ae-8aea-7ab41ca825b5.mp4

**Comment by allinkdev** [comment]
Uploading video_2022-04-12_19-18-19.mp4…
Mason Troy Adams

**Comment by allinkdev** [comment]
> v09044g40000c8h3udbc77uerlnkeb4g.mp4

Mason Troy Adams

**Comment by 1980s-housewife** [comment]
> > v09044g40000c8h3udbc77uerlnkeb4g.mp4
> 
> Mason Troy Adams

Mason Troy Adams

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163188651-ac235035-20eb-48fd-a614-09ffffb3ee84.mp4

**Comment by allinkdev** [comment]
https://github.com/PaperMC/Paper/commit/a9ee1046a50d6ca53b056fa5ef5a0bbb1206964
bozo

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163188842-db017233-09ac-4c83-abb1-c287499484ab.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163189104-45f6ac87-6d46-4d05-8cde-93667d3be7d8.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163189328-f7dad139-4aee-4559-81a1-bce8f3d95a9a.mp4

**Comment by allinkdev** [comment]
https://user-images.githubusercontent.com/44676012/163189339-2d38a356-052f-478d-b6a8-d58b8b44b163.mp4

**Comment by 1980s-housewife** [comment]
https://user-images.githubusercontent.com/17932849/163189614-104703e1-6309-4627-b1ad-1dd3f0697e74.mp4

**Comment by Saturn5Vfive** [comment]
send more memes please

**Comment by veast-network** [comment]
> send more memes please

image

**Pull request merged**
